### ISSUE TITLE
Implement Exponential Scrolling

### ISSUE THREAD

**Issue by j-Ewan** [Up-Mods/OkZoomer#7]
When zoom scrolling, once you get near the numbers around 30+, it seems like it is taking longer to scroll. This could be easily fixed by causing the affects of the scroll to exponentially increase, thereby reversing the decrease in speed that is caused.

**Comment by joaoh1** [comment]
I have "fixed" this issue by making the scroll step above the zoom divisor 1 instead of 0.5, however, an exponential zoom scroll is something that would be nice to have, I'll try to add it later

**Comment by EnnuiL** [comment]
I just got an idea for fixing that; I've experimented with a step-based system, and it makes going from 4 to 50 feel faster
Hopefully, the next content update will have the new system implemented

**Comment by EnnuiL** [comment]
The step-based system has been implemented with the 5.0.0-beta.4 update!

**Comment by EnnuiL** [comment]
Actually, I'm reopening it; While the step system is great, I just realized that with it, I could somehow redistribute those steps in a way where the smaller changes happen with the smaller divisors and bigger ones begin to happen at the end.
Something like 1x 2x 4x 8x 16x etc. can get way too quick to be comfortably used, but by still accounting for the fact that 49x -> 50x is smaller of a change than 1x -> 2x, zooming could get better

**Comment by EnnuiL** [comment]
Exponential zoom scrolling is to be implemented on The Big Update™ Part 1, which will hopefully release tomorrow (on Ok Zoomer's 5th birthday!)

**Comment by EnnuiL** [comment]
Implemented on The Rebirth Update: Part 1 (v10.0.0-beta.7 and v12.0.0-beta.3, v11 pending)
